server:
  port: ${PORT:8080}

spring:
  application:
    name: api_healthy_pet

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    property-naming-strategy: SNAKE_CASE